spring:
  datasource:
    url: "@jdbc.url@"
    username: "@jdbc.username@"
    password: "@jdbc.password@"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
